### ISSUE TITLE
Register for 2022. Store data into separate registration collection. Add registered_at timestamp and add all required fields

### ISSUE THREAD

**Issue by bobbyflowstate** [rajuashok/minty-fam#2]
**Fields for 2022**

- name
- playa name
- phone#
- arrive and leave date
- has_ticket

**Tasks**
- [ ] what other fields? confirm with Rod.
- [x] create registration collection in database and tie the collection to user table
- [ ] add registered_at field which is set on first time user registers
